language: node_js
node_js:
  - "10"

sudo: required

branches:
  only:
    - master

addons:
  apt:
    packages:
      - bash

services:
  - docker

jobs:
  include:
    - stage: test
      before_install:
        - sudo chmod +x pull_worker_images.sh
        - sudo chmod +x build_docker_image.sh
        - sudo chmod +x test_as_docker.sh
      install:
        - npm install
        - ./build_docker_image.sh
      before_script:
        - ./pull_worker_images.sh
      script:
        - npm run test
        - ./test_as_docker.sh

    - stage: build
      before_install:
        - sudo chmod +x build_docker_image.sh
        - sudo chmod +x push_docker_image.sh
      install:
        - ./build_docker_image.sh
      script:
        - ./push_docker_image.sh

    - stage: deploy
      before_script:
        - git config --global user.name "$GITLAB_USER"
        - git config --global user.email "$GITLAB_EMAIL"
      install:
        - git remote rename origin old-origin
        - git remote add origin https://$GITLAB_USERNAME:$GITLAB_ACCESS_TOKEN@$GITLAB_ORIGIN_REPO
        - GIT_SSL_NO_VERIFY=true git push -u origin --all
        - GIT_SSL_NO_VERIFY=true git push -u origin --tags
      script:
        - curl --insecure -X POST -F token=$GITLAB_TOKEN -F ref=$REF_NAME https://gitlab-ce.ctfhub.io/api/v4/projects/3/trigger/pipeline

stages:
  - test
  - name: build
    if: type = push
  - name: deploy
    if: type = push

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - tech@ctfhub.io
